-- Eliminar tablas
DROP TABLE FACTURA_TAB PURGE;
DROP TABLE CARGO_TAB PURGE;
DROP TABLE PEDIDO_PROVEEDOR_TAB PURGE;
DROP TABLE PROVEEDOR_TAB PURGE;
DROP TABLE LINEA_COMPRA_TAB PURGE;
DROP TABLE LINEA_ALQUILER_TAB PURGE;
DROP TABLE CLIENTE_TAB PURGE;
DROP TABLE ADMINISTRADOR_TAB PURGE;
DROP TABLE USUARIO_TAB PURGE;
DROP TABLE DIRECCION_TAB PURGE;
DROP TABLE ALQUILER_TAB PURGE;
DROP TABLE COMPRA_TAB PURGE;
DROP TABLE TRANSACCION_TAB PURGE;
DROP TABLE TARJETA_TAB PURGE;
DROP TABLE EJEMPLARALQUILER_TAB PURGE;
DROP TABLE EJEMPLARVENTA_TAB PURGE;
DROP TABLE LIBRO_TAB PURGE;

-- Eliminar tipos
DROP TYPE FACTURA_OBJ FORCE;
DROP TYPE CARGO_OBJ FORCE;
DROP TYPE PEDIDOS_PROVEEDOR_TABTYP FORCE;
DROP TYPE PEDIDO_PROVEEDOR_OBJ FORCE;
DROP TYPE PROVEEDOR_OBJ FORCE;
DROP TYPE LINEAS_PEDIDO_TABTYP FORCE;
DROP TYPE LINEA_PEDIDO_OBJ FORCE;
DROP TYPE LINEAS_COMPRA_TABTYP FORCE;
DROP TYPE LINEA_COMPRA_OBJ FORCE;
DROP TYPE LINEAS_ALQUILER_TABTYP FORCE;
DROP TYPE LINEA_ALQUILER_OBJ FORCE;
DROP TYPE CLIENTE_OBJ FORCE;
DROP TYPE ADMINISTRADOR_OBJ FORCE;
DROP TYPE USUARIO_OBJ FORCE;
DROP TYPE DIRECCION_OBJ FORCE;
DROP TYPE ALQUILER_OBJ FORCE;
DROP TYPE COMPRA_OBJ FORCE;
DROP TYPE TRANSACCIONES_TABTYP FORCE;
DROP TYPE TRANSACCION_OBJ FORCE;
DROP TYPE TARJETA_OBJ FORCE;
DROP TYPE EJEMPLARALQUILER_OBJ FORCE;
DROP TYPE EJEMPLARVENTA_OBJ FORCE;
DROP TYPE EJEMPLARES_TABTYP FORCE;
DROP TYPE EJEMPLAR_OBJ FORCE;
DROP TYPE LIBROS_TABTYP FORCE;
DROP TYPE LIBRO_OBJ FORCE;

/*
    CREACIÓN DE TIPOS Y TABLAS PARA LAS RELACIONES DE EJEMPLARES - LIBROS
*/

CREATE OR REPLACE TYPE EJEMPLAR_OBJ AS OBJECT (
    Id NUMBER,
    Estado VARCHAR2(50),
    Formato VARCHAR2(50),
    PrecioCoste NUMBER(10,2),
    Disponible VARCHAR2(50),
    DescuentoPremium NUMBER(5,2)
) NOT FINAL;
/

CREATE TYPE EJEMPLARES_TABTYP AS TABLE OF EJEMPLAR_OBJ;
/

CREATE OR REPLACE TYPE LIBRO_OBJ AS OBJECT (
    ISBN VARCHAR2(20),
    Titulo VARCHAR2(40),
    Autor VARCHAR2(255),
    Genero VARCHAR2(100),
    Idioma VARCHAR2(50),
    Sinopsis VARCHAR(255),
    ImagenPortada VARCHAR2(60),
    Ejemplares EJEMPLARES_TABTYP
);
/

CREATE OR REPLACE TYPE LIBROS_TABTYP AS TABLE OF REF LIBRO_OBJ;
/

CREATE TABLE LIBRO_TAB OF LIBRO_OBJ (
    ISBN PRIMARY KEY,
    Titulo NOT NULL,
    Autor NOT NULL
)
NESTED TABLE Ejemplares STORE AS EJEMPLARES_NTAB;
/

CREATE OR REPLACE TYPE EJEMPLARVENTA_OBJ UNDER EJEMPLAR_OBJ (
    PrecioVenta NUMBER(5,2)
);
/

CREATE TABLE EJEMPLARVENTA_TAB OF EJEMPLARVENTA_OBJ(
    CHECK(PrecioVenta > 0)
);
/

CREATE OR REPLACE TYPE EJEMPLARALQUILER_OBJ UNDER EJEMPLAR_OBJ (
    PrecioPorDia NUMBER(5,2),
    DuracionAlquiler NUMBER
);
/

CREATE TABLE EJEMPLARALQUILER_TAB OF EJEMPLARALQUILER_OBJ (
    CHECK(PrecioPorDia > 0),
    CHECK(DuracionAlquiler > 0)
);
/

/*
    CREACIÓN DE TIPOS Y TABLAS PARA TRANSACCIONES
*/

CREATE OR REPLACE TYPE TARJETA_OBJ AS OBJECT(
    Numero NUMBER,
    CVV NUMBER,
    FechaCaducidad DATE
);
/

CREATE TABLE TARJETA_TAB OF TARJETA_OBJ(
    Numero PRIMARY KEY,
    CVV NOT NULL,
    FechaCaducidad NOT NULL
);
/

CREATE OR REPLACE TYPE TRANSACCION_OBJ AS OBJECT(
    IdTransaccion NUMBER,
    Fecha DATE,
    Tarjeta REF TARJETA_OBJ,
    ImporteTotal NUMBER(10,2)
) NOT FINAL;
/

CREATE TABLE TRANSACCION_TAB OF TRANSACCION_OBJ(
    IdTransaccion PRIMARY KEY,
    Fecha NOT NULL,
    CHECK(ImporteTotal > 0)
);
/

CREATE TYPE TRANSACCIONES_TABTYP AS TABLE OF REF TRANSACCION_OBJ;
/

-- HERENCIA DE TRANSACCIÓN (COMPRA Y ALQUILER)

CREATE OR REPLACE TYPE COMPRA_OBJ UNDER TRANSACCION_OBJ (
    Puntos NUMBER
);
/

CREATE TABLE COMPRA_TAB OF COMPRA_OBJ(
    IdTransaccion PRIMARY KEY,
    CHECK(Puntos >= 0)
);
/

CREATE OR REPLACE TYPE ALQUILER_OBJ UNDER TRANSACCION_OBJ (
    IdAlquiler NUMBER,
    FechaInicio DATE
);
/

CREATE TABLE ALQUILER_TAB OF ALQUILER_OBJ(
    IdTransaccion PRIMARY KEY,
    IdAlquiler UNIQUE,
    FechaInicio NOT NULL
);
/

/*
    CREACIÓN DE TIPOS Y TABLAS PARA USUARIOS
*/

CREATE OR REPLACE TYPE DIRECCION_OBJ AS OBJECT(
    TipoDeVia VARCHAR2(255),
    Nombre VARCHAR2(255),
    Numero NUMBER,
    Puerta VARCHAR2(5),
    Piso NUMBER
);
/

CREATE TABLE DIRECCION_TAB OF DIRECCION_OBJ(
    TipoDeVia NOT NULL,
    Nombre NOT NULL,
    Numero NOT NULL
);
/

CREATE OR REPLACE TYPE USUARIO_OBJ AS OBJECT (
    Id NUMBER,
    Nombre VARCHAR2(255),
    CorreoElectronico VARCHAR2(255),
    Contrasena VARCHAR2(255),
    NumeroTlf VARCHAR2(20),
    FechaNacimiento DATE,
    DNI VARCHAR2(20),
    Transacciones TRANSACCIONES_TABTYP,
    Direccion REF DIRECCION_OBJ
) NOT FINAL;
/

CREATE TABLE USUARIO_TAB OF USUARIO_OBJ(
    Id PRIMARY KEY,
    DNI UNIQUE NOT NULL
) NESTED TABLE Transacciones STORE AS TRANSACCIONES_NTAB;
/

CREATE OR REPLACE TYPE CLIENTE_OBJ UNDER USUARIO_OBJ (
    Puntuacion NUMBER,
    TipoCuenta VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE ADMINISTRADOR_OBJ UNDER USUARIO_OBJ (
    FechaDeAlta DATE
);
/

CREATE TABLE CLIENTE_TAB OF CLIENTE_OBJ
    NESTED TABLE Transacciones STORE AS TRANSACCIONES_CLIENTE_NTAB;
/

ALTER TABLE CLIENTE_TAB ADD CONSTRAINT chk_puntuacion CHECK (Puntuacion >= 0);
ALTER TABLE CLIENTE_TAB ADD CONSTRAINT chk_tipocuenta CHECK (TipoCuenta IN ('Basica', 'Premium'));
/

CREATE TABLE ADMINISTRADOR_TAB OF ADMINISTRADOR_OBJ
    NESTED TABLE Transacciones STORE AS TRANSACCIONES_ADMINISTRADOR_NTAB;
/

ALTER TABLE ADMINISTRADOR_TAB MODIFY FechaDeAlta NOT NULL;
/

-- LÍNEAS DE COMPRA Y ALQUILER

CREATE OR REPLACE TYPE LINEA_COMPRA_OBJ AS OBJECT(
    IdLineaCompra NUMBER,
    IdEjemplarVenta REF EJEMPLARVENTA_OBJ,
    Cantidad NUMBER
);
/

CREATE OR REPLACE TYPE LINEAS_COMPRA_TABTYP AS TABLE OF LINEA_COMPRA_OBJ;
/

CREATE TABLE LINEA_COMPRA_TAB OF LINEA_COMPRA_OBJ(
    IdLineaCompra PRIMARY KEY,
    CHECK(Cantidad > 0)
);
/

CREATE OR REPLACE TYPE LINEA_ALQUILER_OBJ AS OBJECT(
    IdLineaAlquiler NUMBER,
    IdEjemplarAlquiler REF EJEMPLARALQUILER_OBJ,
    Cantidad NUMBER
);
/

CREATE OR REPLACE TYPE LINEAS_ALQUILER_TABTYP AS TABLE OF LINEA_ALQUILER_OBJ;
/

CREATE TABLE LINEA_ALQUILER_TAB OF LINEA_ALQUILER_OBJ(
    IdLineaAlquiler PRIMARY KEY,
    CHECK(Cantidad > 0)
);
/

/*
    CREACIÓN DE TABLAS PARA PROVEEDORES Y PEDIDOS
*/

CREATE OR REPLACE TYPE LINEA_PEDIDO_OBJ AS OBJECT(
    Id NUMBER,
    Cantidad NUMBER,
    PrecioUnitario NUMBER(10,2)
);
/

CREATE OR REPLACE TYPE LINEAS_PEDIDO_VARRAYTYP AS VARRAY(100) OF LINEA_PEDIDO_OBJ;
/
-- Lo creamos así porque no se permite doble anidación, por tanto es necesario cambiar la estructura de datos.

CREATE OR REPLACE TYPE PEDIDO_PROVEEDOR_OBJ AS OBJECT(
    Id NUMBER,
    Fecha DATE,
    IdProveedor NUMBER,
    Estado VARCHAR2(50),
    LineasPedido LINEAS_PEDIDO_VARRAYTYP
);
/

CREATE TABLE PEDIDO_PROVEEDOR_TAB OF PEDIDO_PROVEEDOR_OBJ(
    Id PRIMARY KEY,
    Fecha NOT NULL,
    IdProveedor NOT NULL,
    CHECK(Estado IN ('Pendiente', 'Recibido', 'Cancelado'))
);
--NESTED TABLE LineasPedido STORE AS LINEAS_PEDIDO_NTAB; ESTO YA NO ES NECESARIO, usamos el VARRAY.
/

CREATE OR REPLACE TYPE PEDIDOS_PROVEEDOR_TABTYP AS TABLE OF PEDIDO_PROVEEDOR_OBJ;
/

CREATE OR REPLACE TYPE PROVEEDOR_OBJ AS OBJECT(
    Id NUMBER,
    Email VARCHAR2(255),
    Nombre VARCHAR2(255),
    Telefono VARCHAR2(20),
    Pedidos PEDIDOS_PROVEEDOR_TABTYP
);
/

CREATE TABLE PROVEEDOR_TAB OF PROVEEDOR_OBJ(
    Id PRIMARY KEY,
    Nombre NOT NULL
)
NESTED TABLE Pedidos STORE AS PEDIDOS_PROVEEDOR_NTAB;
/

/*
    CREACIÓN DE TIPOS Y TABLAS PARA FACTURAS
*/

CREATE OR REPLACE TYPE FACTURA_OBJ AS OBJECT(
    IdFactura NUMBER,
    PrecioTotal NUMBER,
    Comentario VARCHAR2(255),
    FechaEmision DATE,
    FechaVencimiento DATE,
    CosteEnvio NUMBER(5,2),
    Transacciones TRANSACCIONES_TABTYP,
    LineasCompra LINEAS_COMPRA_TABTYP,
    LineasAlquiler LINEAS_ALQUILER_TABTYP
);
/

CREATE TABLE FACTURA_TAB OF FACTURA_OBJ(
    IdFactura PRIMARY KEY,
    FechaEmision NOT NULL,
    FechaVencimiento NOT NULL
) 
NESTED TABLE LineasCompra STORE AS LINEAS_COMPRA_NTAB,
NESTED TABLE LineasAlquiler STORE AS LINEAS_ALQUILER_NTAB,
NESTED TABLE Transacciones STORE AS TRANSACCIONES2_NTAB;
/

ALTER TABLE FACTURA_TAB ADD CONSTRAINT chk_precio_total CHECK (PrecioTotal > 0);
ALTER TABLE FACTURA_TAB ADD CONSTRAINT chk_coste_envio CHECK (CosteEnvio > 0);
/

CREATE OR REPLACE TYPE CARGO_OBJ AS OBJECT (
    IdCargo NUMBER,
    Importe NUMBER(5,2),
    Fecha DATE,
    Alquiler REF ALQUILER_OBJ
);
/

CREATE TABLE CARGO_TAB OF CARGO_OBJ (
    IdCargo PRIMARY KEY,
    CHECK(Importe > 0),
    Fecha NOT NULL
);
/