-- Primero eliminamos las tablas
DROP TABLE FACTURA_TAB CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR_TAB CASCADE CONSTRAINTS;
DROP TABLE PEDIDOPROVEEDOR_TAB CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR_TAB CASCADE CONSTRAINTS;
DROP TABLE CLIENTE_TAB CASCADE CONSTRAINTS;
DROP TABLE ALQUILER_TAB CASCADE CONSTRAINTS;
DROP TABLE COMPRA_TAB CASCADE CONSTRAINTS;
DROP TABLE LIBRO_TAB CASCADE CONSTRAINTS;
DROP TABLE TARJETA_TAB CASCADE CONSTRAINTS;
DROP TABLE DIRECCION_TAB CASCADE CONSTRAINTS;

-- Luego eliminamos los tipos en orden inverso a su creación

-- Tipos tabla
DROP TYPE RESENAS_NTABTYP FORCE;
DROP TYPE LINEA_ALQUILER_NTABTYP FORCE;
DROP TYPE LINEA_COMPRA_NTABTYP FORCE;
DROP TYPE LINEASPEDIDO_NTABTYP FORCE;
DROP TYPE EJEMPLARESVENTA_NTABTYP FORCE;
DROP TYPE EJEMPLARESALQUILER_NTABTYP FORCE;
DROP TYPE COMPRA_NTABTYP FORCE;
DROP TYPE ALQUILER_NTABTYP FORCE;

-- Tipos objetos finales
DROP TYPE RESENA_OBJ FORCE;
DROP TYPE FACTURA_OBJ FORCE;
DROP TYPE PEDIDOPROVEEDOR_OBJ FORCE;
DROP TYPE ADMINISTRADOR_OBJ FORCE;
DROP TYPE CLIENTE_OBJ FORCE;
DROP TYPE USUARIO_OBJ FORCE;
DROP TYPE ALQUILER_OBJ FORCE;
DROP TYPE COMPRA_OBJ FORCE;
DROP TYPE LINEA_ALQUILER_OBJ FORCE;
DROP TYPE LINEA_COMPRA_OBJ FORCE;
DROP TYPE TRANSACCION_OBJ FORCE;
DROP TYPE LINEAPEDIDO_OBJ FORCE;
DROP TYPE LIBRO_OBJ FORCE;
DROP TYPE EJEMPLAR_ALQUILER_OBJ FORCE;
DROP TYPE EJEMPLAR_VENTA_OBJ FORCE;
DROP TYPE EJEMPLAR_OBJ FORCE;
DROP TYPE CARGO_OBJ FORCE;
DROP TYPE PROVEEDOR_OBJ FORCE;
DROP TYPE TARJETA_OBJ FORCE;
DROP TYPE DIRECCION_OBJ FORCE;