DROP TABLE PROVEEDOR_TAB PURGE;
DROP TABLE PEDIDOS_TAB PURGE;
DROP TABLE CATEGORIA_TAB PURGE;
DROP TABLE PRODUCTOS_TAB PURGE;

DROP TYPE PROVEEDOR_OBJ FORCE;
DROP TYPE SUMINISTRO_OBJ FORCE;
DROP TYPE SUMINISTROS_TABTYP FORCE;
DROP TYPE ALMACEN_OBJ FORCE;
DROP TYPE PRODUCTO_OBJ FORCE;
DROP TYPE PRODUCTOS_TABTYP FORCE;
DROP TYPE PERECEDERO_OBJ FORCE;
DROP TYPE PEDIDO_OBJ FORCE;
DROP TYPE LINEA_PEDIDO_OBJ FORCE;
DROP TYPE LINEAS_PEDIDO_TABTYP FORCE;






CREATE OR REPLACE TYPE PROVEEDOR_OBJ AS OBJECT(
    CIF NUMBER
);
/

CREATE TABLE PROVEEDOR_TAB OF PROVEEDOR_OBJ(
    CIF PRIMARY KEY
);
/

CREATE OR REPLACE TYPE SUMINISTRO_OBJ AS OBJECT(
    PRECIO NUMBER,
    DESCUENTO NUMBER,
    PROVEEDOR REF PROVEEDOR_OBJ
);
/

CREATE OR REPLACE TYPE SUMINISTROS_TABTYP AS TABLE OF SUMINISTRO_OBJ;
/

CREATE OR REPLACE TYPE ALMACEN_OBJ AS OBJECT(
    CANTIDAD NUMBER,
    UMBRAL NUMBER,
    PRECIO NUMBER
);
/

CREATE OR REPLACE TYPE PRODUCTO_OBJ AS OBJECT(
    CODIGO_PRODUCTO NUMBER,
    ALMACEN ALMACEN_OBJ,
    SUMINISTRO SUMINISTROS_TABTYP
)NOT FINAL;
/

CREATE OR REPLACE TYPE PERECEDERO_OBJ UNDER PRODUCTO_OBJ(
    CONSERVACION VARCHAR2(255),
    DURACION NUMBER
);
/

CREATE TABLE PRODUCTOS_TAB OF PRODUCTO_OBJ(
    CODIGO_PRODUCTO PRIMARY KEY
)NESTED TABLE SUMINISTRO STORE AS SUMINISTROS_NTAB;
/

CREATE OR REPLACE TYPE LINEA_PEDIDO_OBJ AS OBJECT(
    NUMERO_LINEA NUMBER
);
/

CREATE OR REPLACE TYPE LINEAS_PEDIDO_TABTYP AS TABLE OF LINEA_PEDIDO_OBJ;
/

CREATE OR REPLACE TYPE PEDIDO_OBJ AS OBJECT(
    NUMERO_PEDIDO NUMBER,
    LINEAS_PEDIDO LINEAS_PEDIDO_TABTYP
);
/

CREATE TABLE PEDIDOS_TAB OF PEDIDO_OBJ(
    NUMERO_PEDIDO PRIMARY KEY
)NESTED TABLE LINEAS_PEDIDO STORE AS LINEAS_PEDIDO_NTAB(
    PRIMARY KEY(NESTED_TABLE_ID, NUMERO_LINEA)
);
/

CREATE OR REPLACE TYPE PRODUCTOS_TABTYP AS TABLE OF PRODUCTO_OBJ;

CREATE OR REPLACE TYPE CATEGORIA_OBJ AS OBJECT(
    NOMBRE VARCHAR2(255),
    PRODUCTOS PRODUCTOS_TABTYP
);
/

CREATE TABLE CATEGORIA_TAB OF CATEGORIA_OBJ(
    NOMBRE PRIMARY KEY
)NESTED TABLE PRODUCTOS STORE AS PRODUCTOS_NTAB;
/