-- Insertar direcciones
INSERT INTO DIRECCION_TAB (DIRECCION_OBJ)
VALUES ('Calle', 'Mayor', 10, 2, 'B', 'Madrid');

INSERT INTO DIRECCION_TAB (TIPODEVIA, NOMBRE, NUMERO, PISO, PUERTA, LOCALIDAD)
VALUES ('Avenida', 'Andalucía', 25, 3, 'A', 'Sevilla');


-- Insertar tarjetas
INSERT INTO TARJETA_TAB (NUMERO, CVV, FECHACADUCIDAD)
VALUES (1234567890123456, 123, TO_DATE('12/2026', 'MM/YYYY'));

INSERT INTO TARJETA_TAB (NUMERO, CVV, FECHACADUCIDAD)
VALUES (9876543210987654, 456, TO_DATE('11/2025', 'MM/YYYY'));


-- Insertar proveedores
INSERT INTO PROVEEDOR_TAB (ID, NOMBRE, EMAIL, TELEFONO)
VALUES (1, 'Editorial Planeta', 'contacto@planeta.es', 912345678);

INSERT INTO PROVEEDOR_TAB (ID, NOMBRE, EMAIL, TELEFONO)
VALUES (2, 'Editorial Anaya', 'info@anaya.es', 923456789);

COMMIT;

INSERT INTO LIBRO_TAB
VALUES('0123456789124', 'Helou', 'yo', 'drama', 'castellano', 'una historia de miedo', 'image.png', EJEMPLARESVENTA_NTABTYP(), EJEMPLARESALQUILER_NTABTYP(), (SELECT REF(p) FROM PROVEEDOR_TAB p WHERE p.ID = 2));