CREATE OR REPLACE TYPE EJEMPLAR_OBJ AS OBJECT (
    ID NUMBER,
    ESTADO VARCHAR2(20),
    FORMATO VARCHAR2(20),
    PRECIOCOSTE NUMBER,
    DISPONIBILE BOOLEAN,
    DESCUENTOPREMIUM NUMBER
);

CREATE OR REPLACE TYPE EJEMPLARES_NTABTYP AS TABLE OF EJEMPLAR_OBJ;

CREATE OR REPLACE TYPE PROVEEDOR_OBJ AS OBJECT (
    ID NUMBER,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(50),
    TELEFONO NUMBER
);

CREATE OR REPLACE TYPE LIBRO_OBJ AS OBJECT (
    ISBN CHAR(13),
    TITULO VARCHAR2(100),
    AUTOR VARCHAR2(100),
    GENERO VARCHAR2(20),
    IDIOMA VARCHAR2(20),
    SINOPSIS VARCHAR2(500),
    IMAGENPORTADA VARCHAR2(100),
    EJEMPLARES EJEMPLARES_NTABTYP,
    PROVEEDOR REF PROVEEDOR_OBJ
);

CREATE OR REPLACE TYPE LINEAPEDIDO_OBJ AS OBJECT (
    NLINEA NUMBER,
    CANTIDAD NUMBER,
    PRECIOUNITARIO NUMBER,
    LIBRO REF LIBRO_OBJ
);

CREATE OR REPLACE TYPE LINEASPEDIDO_NTABTYP AS TABLE OF LINEAPEDIDO_OBJ;

CREATE OR REPLACE TYPE DIRECCION_OBJ AS OBJECT (
    TIPODEVIA VARCHAR2(20),
    NOMBRE VARCHAR2(100),
    NUMERO NUMBER,
    PISO NUMBER,
    PUERTA VARCHAR2(10),
    LOCALIDAD VARCHAR2(50)
);

CREATE OR REPLACE TYPE USUARIO_OBJ AS OBJECT (
    ID NUMBER,
    NOMBRE VARCHAR2(100),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    EMAIL VARCHAR2(50),
    CONTRASENA VARCHAR2(20),
    TELEFONO NUMBER,
    FECHANACIMIENTO DATE,
    DNI CHAR(9)
);

CREATE OR REPLACE TYPE CLIENTES_OBJ UNDER USUARIO_OBJ (
    PUNTUACION NUMBER,
    TIPOCUENTA VARCHAR2(20)
);

CREATE OR REPLACE TYPE ADMINISTRADOR_OBJ UNDER USUARIO_OBJ (
    FECHAALTA DATE
);

CREATE OR REPLACE TYPE PEDIDOPROVEEDOR_OBJ AS OBJECT (
    ID NUMBER,
    FECHA DATE,
    ESTADO VARCHAR2(20),
    LINEAS LINEASPEDIDO_NTABTYP,
    DIRECCION REF DIRECCION_OBJ,
    PROVEEDOR REF PROVEEDOR_OBJ,
    ADMINISTRADOR REF ADMINISTRADOR_OBJ
);

