CREATE OR REPLACE TYPE DIRECCION_OBJ AS OBJECT (
    TIPODEVIA VARCHAR2(20),
    NOMBRE VARCHAR2(100),
    NUMERO NUMBER,
    PISO NUMBER,
    PUERTA VARCHAR2(10),
    LOCALIDAD VARCHAR2(50)
);
/

CREATE OR REPLACE TYPE TARJETA_OBJ AS OBJECT (
    NUMERO NUMBER,
    CVV NUMBER,
    FECHACADUCIDAD DATE
);
/

CREATE OR REPLACE TYPE PROVEEDOR_OBJ AS OBJECT (
    ID NUMBER,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(50),
    TELEFONO NUMBER
);
/

CREATE OR REPLACE TYPE CARGO_OBJ AS OBJECT(
    IMPORTE NUMBER,
    FECHA DATE
);
/

CREATE OR REPLACE TYPE EJEMPLAR_OBJ AS OBJECT (
    ID NUMBER,
    ESTADO VARCHAR2(20),
    FORMATO VARCHAR2(20),
    PRECIOCOSTE NUMBER,
    DISPONIBILE NUMBER(1),
    DESCUENTOPREMIUM NUMBER
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE EJEMPLAR_VENTA_OBJ UNDER EJEMPLAR_OBJ(
    PRECIO_VENTA NUMBER
);
/

CREATE OR REPLACE TYPE EJEMPLAR_ALQUILER_OBJ UNDER EJEMPLAR_OBJ(
    PRECIO_POR_DIA NUMBER,
    DURACION_ALQUILER NUMBER
);
/

CREATE OR REPLACE TYPE EJEMPLARESVENTA_NTABTYP AS TABLE OF EJEMPLAR_VENTA_OBJ;
/

CREATE OR REPLACE TYPE EJEMPLARESALQUILER_NTABTYP AS TABLE OF EJEMPLAR_ALQUILER_OBJ;
/

CREATE OR REPLACE TYPE LIBRO_OBJ AS OBJECT (
    ISBN CHAR(13),
    TITULO VARCHAR2(100),
    AUTOR VARCHAR2(100),
    GENERO VARCHAR2(20),
    IDIOMA VARCHAR2(20),
    SINOPSIS VARCHAR2(500),
    IMAGENPORTADA VARCHAR2(100),
    EJEMPLARESVENTA EJEMPLARESVENTA_NTABTYP,
    EJEMPLARESALQUILER EJEMPLARESALQUILER_NTABTYP,
    PROVEEDOR REF PROVEEDOR_OBJ
);
/

CREATE OR REPLACE TYPE LINEAPEDIDO_OBJ AS OBJECT (
    NLINEA NUMBER,
    CANTIDAD NUMBER,
    PRECIOUNITARIO NUMBER,
    LIBRO REF LIBRO_OBJ
);
/

CREATE OR REPLACE TYPE LINEASPEDIDO_NTABTYP AS TABLE OF LINEAPEDIDO_OBJ;
/

CREATE OR REPLACE TYPE USUARIO_OBJ AS OBJECT (
    ID NUMBER,
    NOMBRE VARCHAR2(100),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    EMAIL VARCHAR2(50),
    CONTRASENA VARCHAR2(20),
    TELEFONO NUMBER,
    FECHANACIMIENTO DATE,
    DNI CHAR(9),
    DIRECCION REF DIRECCION_OBJ
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE CLIENTE_OBJ UNDER USUARIO_OBJ (
    PUNTUACION NUMBER,
    TIPOCUENTA VARCHAR2(20)
);
/

CREATE OR REPLACE TYPE ADMINISTRADOR_OBJ UNDER USUARIO_OBJ (
    FECHAALTA DATE
);
/

CREATE OR REPLACE TYPE RESENA_OBJ AS OBJECT (
    ID NUMBER,
    TEXTO VARCHAR2(500),
    PUNTUACION NUMBER,
    ESTRELLAS NUMBER,
    CLIENTE REF CLIENTE_OBJ,
    REVISOR REF ADMINISTRADOR_OBJ
);
/

CREATE OR REPLACE TYPE RESENAS_NTABTYP AS TABLE OF RESENA_OBJ;
/

CREATE OR REPLACE TYPE TRANSACCION_OBJ AS OBJECT (
    ID NUMBER,
    FECHA DATE,
    IMPORTE NUMBER,
    TIPO VARCHAR2(20),
    COSTEENVIO NUMBER,
    TARJETA REF TARJETA_OBJ,
    DIRECCION REF DIRECCION_OBJ,
    USUARIO REF USUARIO_OBJ
) NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE LINEA_COMPRA_OBJ AS OBJECT (
    ID_LINEACOMPRA NUMBER,
    EJEMPLAR_COMPRA REF EJEMPLAR_VENTA_OBJ,
    CANTIDAD NUMBER,
    RESENA RESENA_OBJ
);
/

CREATE OR REPLACE TYPE LINEA_COMPRA_NTABTYP AS TABLE OF LINEA_COMPRA_OBJ;
/

CREATE OR REPLACE TYPE LINEA_ALQUILER_OBJ AS OBJECT (
    ID_LINEAALQUILER NUMBER,
    EJEMPLAR_ALQUILER REF EJEMPLAR_ALQUILER_OBJ,
    CANTIDAD NUMBER,
    RESENA RESENA_OBJ
);
/

CREATE OR REPLACE TYPE LINEA_ALQUILER_NTABTYP AS TABLE OF LINEA_ALQUILER_OBJ;
/

CREATE OR REPLACE TYPE COMPRA_OBJ UNDER TRANSACCION_OBJ(
    PUNTOS NUMBER,
    LINEA_COMPRA LINEA_COMPRA_NTABTYP
);
/

CREATE OR REPLACE TYPE COMPRA_NTABTYP AS TABLE OF REF COMPRA_OBJ;
/

CREATE OR REPLACE TYPE ALQUILER_OBJ UNDER TRANSACCION_OBJ(
    FECHAINICIO DATE,
    CARGO CARGO_OBJ,
    LINEA_ALQUILER LINEA_ALQUILER_NTABTYP
);
/

CREATE OR REPLACE TYPE ALQUILER_NTABTYP AS TABLE OF REF ALQUILER_OBJ;
/

CREATE OR REPLACE TYPE PEDIDOPROVEEDOR_OBJ AS OBJECT (
    ID NUMBER,
    FECHA DATE,
    ESTADO VARCHAR2(20),
    LINEAS_PEDIDO LINEASPEDIDO_NTABTYP,
    DIRECCION REF DIRECCION_OBJ,
    PROVEEDOR REF PROVEEDOR_OBJ,
    ADMINISTRADOR REF ADMINISTRADOR_OBJ
);
/

CREATE OR REPLACE TYPE FACTURA_OBJ AS OBJECT (
    ID NUMBER,
    PRECIO_TOTAL NUMBER,
    COMENTARIO VARCHAR2(255),
    FECHA_EMISION DATE,
    FECHA_VENCIMIENTO DATE,
    COMPRAS COMPRA_NTABTYP,
    ALQUILERES ALQUILER_NTABTYP
);
/

CREATE TABLE LIBRO_TAB OF LIBRO_OBJ(
    ISBN PRIMARY KEY,
    TITULO NOT NULL,
    AUTOR NOT NULL
) NESTED TABLE EJEMPLARESVENTA STORE AS EJEMPLARESVENTA_NTAB,
  NESTED TABLE EJEMPLARESALQUILER STORE AS EJEMPLARESALQUILER_NTAB;


CREATE TABLE COMPRA_TAB OF COMPRA_OBJ(
    ID PRIMARY KEY
) NESTED TABLE LINEA_COMPRA STORE AS LINEASCOMPRA_NTAB;


CREATE TABLE ALQUILER_TAB OF ALQUILER_OBJ(
    ID PRIMARY KEY
) NESTED TABLE LINEA_ALQUILER STORE AS LINEASALQUILER_NTAB;


CREATE TABLE CLIENTE_TAB OF CLIENTE_OBJ(
    DNI PRIMARY KEY
);


CREATE TABLE ADMINISTRADOR_TAB OF ADMINISTRADOR_OBJ(
    DNI PRIMARY KEY
);


CREATE TABLE PEDIDOPROVEEDOR_TAB OF PEDIDOPROVEEDOR_OBJ(
    ID PRIMARY KEY
) NESTED TABLE LINEAS_PEDIDO STORE AS LINEASPEDIDOPROVEEDOR_NTAB;


CREATE TABLE PROVEEDOR_TAB OF PROVEEDOR_OBJ(
    ID PRIMARY KEY
);


CREATE TABLE FACTURA_TAB OF FACTURA_OBJ(
    ID PRIMARY KEY
) NESTED TABLE COMPRAS STORE AS COMPRAS_NTAB
  NESTED TABLE ALQUILERES STORE AS ALQUILERES_NTAB;


CREATE TABLE TARJETA_TAB OF TARJETA_OBJ(
    NUMERO PRIMARY KEY
);


CREATE TABLE DIRECCION_TAB OF DIRECCION_OBJ(
    TIPODEVIA NOT NULL,
    NOMBRE NOT NULL,
    LOCALIDAD NOT NULL
);
